### ISSUE TITLE
ng add fails to work with Angular 11.1.x

### ISSUE THREAD

**Issue by ridyio** [ngneat/tailwind#57]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After running ng add command it throws an exception and doesn't do the work successfully.

## Expected behavior

It would finish the process.

## Minimal reproduction of the problem with instructions

After updating angular-cli to latest create a new project with `ng new` command and then run the `ng add @ngneat/tailwind` command in the folder. It would crash with below message:

<pre><code>
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
Require stack:
- /Users/xxxxxxxx/node_modules/@ngneat/tailwind/src/utils/normalize-options-ng.js
- /Users/xxxxxxxx/node_modules/@ngneat/tailwind/src/schematics/ng-add/ng-add.js
- /Users/xxxxxxxx/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/xxxxxxxx/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/xxxxxxxx/node_modules/@angular/cli/utilities/json-schema.js
- /Users/xxxxxxxx/node_modules/@angular/cli/models/command-runner.js
- /Users/xxxxxxxx/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
See "/private/tmp/ng-jz5Ggc/angular-errors.log" for further details.
</code></pre>

## What is the motivation / use case for changing the behavior?

I think this is a compatibility issue with newer version of angular.

## Environment

<pre><code>
Angular version: 11.1.x

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 15.3.0
- Platform:  Mac
</code></pre>

**Comment by beeman** [comment]
Issue confirmed on my machine with a new Ng 11 project.

A quick analysis..

The problem is [here](https://github.com/ngneat/tailwind/blob/main/libs/tailwind/src/utils/normalize-options-ng.ts#L2).

It looks like the method `getWorkspace` changed a bit, it's exported from somewhere else and now returns a Promise.

<img width="789" alt="Screen Shot 2021-01-23 at 4 07 28" src="https://user-images.githubusercontent.com/36491/105574139-91270900-5d30-11eb-8067-62f86b44147b.png">

Not sure what the best fix would be. 

As far as I know, @ngneat/tailwind doesn't currently depend on any specific version of this so it will use whatever exists in the workspace.

**Comment by ridyio** [comment]
@beeman Thanks for confirmation, In my case it was config module not being available anymore in Angular 11.1. As a workaround for now i did installed @schematics v10.2. added this library and updated back to 11.1.1.
`npm i @schematics/angular@10.2.0`

**Comment by vltansky** [comment]
@beeman 
This is the commit with changes:
https://github.com/angular/angular-cli/commit/6ff04473ef10d3dfe8cb13f26a65e8826930b0f4#diff-2740741169dc6046fa1273c3841fcf3812646f415c89a1f7c485165f6b74e8aa

Guess we should rewrite schematics to `await getWorkspace()`, as its done here:
https://github.com/angular/angular-cli/commit/6ff04473ef10d3dfe8cb13f26a65e8826930b0f4#diff-99c33e4d3fb777da09abfcde1cecce7d6a43d58c62fc83e273b2e733de96119aR23-R24

**Comment by beeman** [comment]
@vltansky I think we either pin the versions, or alternatively avoid importing this from @schematics/angular all together and provide a local implementation of this method as a helper function.  I think the last option is more user friendly and future proof, but it does add some more code to maintain. 

Curious about what @nartc thinks works best/prefers.

**Comment by vltansky** [comment]
There is also a difference in dependencies that we need to install for different angular versions:
`> v11.1` - only tailwindcss and selected plugins
`< v11.1` - postcss 8
`< v11` - postcss 8, postcss-import, postcss-loader, autoprefixer

**Comment by nartc** [comment]
@beeman `getWorkspace()` should be imported from `@schematics/angular/utility/workspace` instead. `getWorkspace()` from `utility/workspace` returns a Promise and is identical to the one from Nx, and should work with previous AND future versions. We can fix the one in `normalizeOptions` util to use that instead.

@vltansky I'm aware of those libraries change and sadly I don't think it makes much sense to maintain logic to differentiate those. 

That said, I'll be fixing the bug with `getWorkspace()` then publish a new patch release and will mark that one for Angular < v11.1. Then I'll be removing `postcss` from dependencies list and publish a v6 to support latest version of Angular. What do you guys think?

**Comment by beeman** [comment]
@nartc I like that, probably easiest and best for the library to keep it moving forward quickly and don't try to support all Angular versions at each @ngneat/tailwind release.

**Comment by vltansky** [comment]
I agree, but I think we should at least mention this in readme.

**Comment by nartc** [comment]
Fixed with 5.2.4
