### ISSUE TITLE
6.0.3: Cannot find module 'postcss-ng-tailwind-in-components'

### ISSUE THREAD

**Issue by JulianBerger** [ngneat/tailwind#74]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After updating to 6.0.3 I get the following error with ng serve:
```
Error: ./src/assets/social-logos-svg.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "postcss-ng-tailwind-in-components" plugin failed: Cannot find module 'postcss-ng-tailwind-in-components'
```

After downgrading to 6.0.2 the error disappears and everything works again...

## Environment

<pre><code>
Angular version: 11.1.2

For Tooling issues:
- Node version: 14.15.4  
- Platform:  MacOS 10.15
</code></pre>

**Comment by ridyio** [comment]
Install the aforementioned module and this gets fixed. It's a peer dependency in newer versions i think.
